-- Canonical schema for this app (matches src/lib/db/repos.ts).
-- New database: run this once on empty public schema, then import CSV in FK order.
-- See docs/database-schema-and-postgres-migration.md for \copy notes.

-- 1) departments
CREATE TABLE public.departments (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text        NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- 2) menu — todays_special FK added after meals
CREATE TABLE public.menu (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            text        NOT NULL,
  date            date        NOT NULL,
  deadline        timestamptz NOT NULL,
  status          text        NOT NULL DEFAULT 'upcoming',
  todays_special  bigint NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT menu_status_check CHECK (status IN ('active', 'completed', 'upcoming'))
);

-- 3) meals
CREATE TABLE public.meals (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text        NOT NULL,
  description  text        NOT NULL DEFAULT '',
  menu_id      bigint      NOT NULL REFERENCES public.menu (id) ON DELETE CASCADE,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_meals_menu_id ON public.meals (menu_id);

-- 4) menu.todays_special → meals
ALTER TABLE public.menu
  ADD CONSTRAINT menu_todays_special_fkey
  FOREIGN KEY (todays_special) REFERENCES public.meals (id) ON DELETE SET NULL;

-- 5) users
CREATE TABLE public.users (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text        NOT NULL,
  department  bigint      NOT NULL REFERENCES public.departments (id) ON DELETE RESTRICT,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_department ON public.users (department);

-- 6) selections
CREATE TABLE public.selections (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  meal_id     bigint NOT NULL REFERENCES public.meals (id) ON DELETE CASCADE,
  opted_in    boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_selections_user_id ON public.selections (user_id);
CREATE INDEX idx_selections_meal_id ON public.selections (meal_id);

-- Keep updated_at in sync on row changes (app also sets it on some paths)
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS selections_set_updated_at ON public.selections;
CREATE TRIGGER selections_set_updated_at
  BEFORE UPDATE ON public.selections
  FOR EACH ROW
  EXECUTE PROCEDURE public.set_updated_at();
