-- Add GENERATED BY DEFAULT AS IDENTITY to bigint primary keys so API INSERTs
-- can omit `id` (fixes: null value in column "id" violates not-null constraint).
-- Idempotent: safe to re-run if identity is already present.

CREATE OR REPLACE FUNCTION _migration_001_identity_on_column(
  sch text,
  tbl text,
  col text
) RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  is_identity boolean;
  seq text;
  mx bigint;
  hr boolean;
BEGIN
  SELECT (a.attidentity = ANY (ARRAY['a'::"char", 'd'::"char"]))
  INTO is_identity
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = sch
    AND c.relname = tbl
    AND a.attname = col
    AND a.attnum > 0
    AND NOT a.attisdropped;

  IF is_identity THEN
    RETURN;
  END IF;

  EXECUTE format(
    'ALTER TABLE %I.%I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
    sch,
    tbl,
    col
  );

  seq := pg_get_serial_sequence(sch || '.' || tbl, col);
  IF seq IS NULL THEN
    RAISE EXCEPTION 'no sequence for %.% column % after adding identity', sch, tbl, col;
  END IF;

  EXECUTE format('SELECT MAX(%I) FROM %I.%I', col, sch, tbl) INTO mx;
  EXECUTE format('SELECT EXISTS (SELECT 1 FROM %I.%I)', sch, tbl) INTO hr;

  PERFORM setval(seq::regclass, COALESCE(mx, 0), hr);
END;
$$;

SELECT _migration_001_identity_on_column('public', 'departments', 'id');
SELECT _migration_001_identity_on_column('public', 'menu', 'id');
SELECT _migration_001_identity_on_column('public', 'meals', 'id');
SELECT _migration_001_identity_on_column('public', 'users', 'id');
SELECT _migration_001_identity_on_column('public', 'selections', 'id');

DROP FUNCTION _migration_001_identity_on_column(text, text, text);
